import React from 'react'
import IcoMoon, { IconProps } from 'react-icomoon'
import iconSet from '../../../public/images/jomnot-icon.json'

interface Props extends IconProps {
  icon: IconName
}

const Icon = (props: Props) => {
  // console.log(JSON.stringify(iconList(iconSet)), null, 2)
  return <IcoMoon iconSet={iconSet} {...props} />
}

export default Icon

type IconName =
  | 'minus'
  | 'plus'
  | 'hamburger-menu'
  | 'campground'
  | 'martini-glass-citrus'
  | 'umbrella-beach'
  | 'Apple'
  | 'Google'
  | 'Telegram'
  | 'Tiktok'
  | 'YouTube'
  | 'Instagram'
  | 'Twitter'
  | 'Facebook'
  | 'jomnot-rounded-black'
  | 'jomnot-rounded-white'
  | 'jomnot-square-white'
  | 'jomnot-square-black'
  | 'jomnot-black'
  | 'jomnot-white'
  | 'home-Filled'
  | 'search-Filled'
  | 'heart-Filled'
  | 'eye-Filled'
  | 'eye-slash-Filled'
  | 'times-square-Filled'
  | 'plus-square-Filled'
  | 'minus-square-Filled'
  | 'question-circle-Filled'
  | 'exclamation-circle-Filled'
  | 'info-circle-Filled'
  | 'check-circle-Filled'
  | 'log-in-Filled'
  | 'log-out-Filled'
  | 'globe-Filled'
  | 'settings-Filled'
  | 'trash-Filled'
  | 'pen-Filled'
  | 'bell-Filled'
  | 'bell-slash-Filled'
  | 'star-Filled'
  | 'filter-Filled'
  | 'tag-Filled'
  | 'sort-descending-Filled'
  | 'sort-ascending-Filled'
  | 'more-h-circle-Filled'
  | 'more-v-circle-Filled'
  | 'clock-Filled'
  | 'calendar-Filled'
  | 'copy-Filled'
  | 'download-Filled'
  | 'upload-Filled'
  | 'user-Filled'
  | 'users-Filled'
  | 'users-three-Filled'
  | 'map-marker-Filled'
  | 'map-pin-Filled'
  | 'map-Filled'
  | 'compass-Filled'
  | 'comments-Filled'
  | 'envelope-Filled'
  | 'image-Filled'
  | 'film-Filled'
  | 'phone-Filled'
  | 'arrow-left-Filled'
  | 'arrow-right-Filled'
  | 'arrow-up-Filled'
  | 'arrow-down-Filled'
  | 'chevron-left-Filled'
  | 'chevron-right-Filled'
  | 'chevron-up-Filled'
  | 'chevron-down-Filled'
  | 'chevron-circle-left-Filled'
  | 'chevron-circle-right-Filled'
  | 'chevron-circle-up-Filled'
  | 'chevron-circle-down-Filled'
  | 'times-square-Bold'
  | 'home-Bold'
  | 'search-Bold'
  | 'heart-Bold'
  | 'eye-Bold'
  | 'eye-slash-Bold'
  | 'plus-square-Bold'
  | 'minus-square-Bold'
  | 'question-circle-Bold'
  | 'exclamation-circle-Bold'
  | 'info-circle-Bold'
  | 'check-circle-Bold'
  | 'log-in-Bold'
  | 'log-out-Bold'
  | 'globe-Bold'
  | 'settings-Bold'
  | 'trash-Bold'
  | 'pen-Bold'
  | 'bell-Bold'
  | 'bell-slash-Bold'
  | 'star-Bold'
  | 'filter-Bold'
  | 'tag-Bold'
  | 'sort-descending-Bold'
  | 'sort-ascending-Bold'
  | 'more-v-circle-Bold_3'
  | 'more-v-circle-Bold'
  | 'clock-Bold'
  | 'calendar-Bold'
  | 'copy-Bold'
  | 'download-Bold'
  | 'upload-Bold'
  | 'user-Bold'
  | 'users-Bold'
  | 'users-three-Bold'
  | 'map-marker-Bold'
  | 'map-pin-Bold'
  | 'map-Bold'
  | 'compass-Bold'
  | 'comments-Bold'
  | 'envelope-Bold'
  | 'image'
  | 'film-Bold'
  | 'phone-Bold'
  | 'arrow-left-Bold'
  | 'arrow-right-Bold'
  | 'arrow-up-Bold'
  | 'arrow-down-Bold'
  | 'chevron-left-Bold'
  | 'chevron-right-Bold'
  | 'chevron-up-Bold'
  | 'chevron-down-Bold'
  | 'chevron-circle-left-Bold'
  | 'chevron-circle-right-Bold'
  | 'chevron-circle-up-Bold'
  | 'chevron-circle-down-Bold'
